[package]
name = "opentitan-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "^1.0"
proc-macro2 = "^1.0"
syn = { version = "^1.0", features = ["full", "extra-traits"] }
deser-hjson = "^1.1"
serde = "^1.0"
tock-registers = "^0.8"
