[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { version = "*", default-features = false, features = ["ecdsa"] }
opentitan-lib = { path = "../opentitan-lib" }
